#! /bin/bash
#$ -cwd
#$ -S /bin/bash
#$ -V
#$ -t 1-188
#$ -q all.q
#$ -pe mpi_smp 1
#$ -e /home2/data/Projects/CWAS/share/adhd200_rerun/02_preprocess/cluster_temp_files/c-pac_2013_04_24_10_31_07.err
#$ -o /home2/data/Projects/CWAS/share/adhd200_rerun/02_preprocess/cluster_temp_files/c-pac_2013_04_24_10_31_07.out
source ~/.bashrc
python -c "import CPAC; CPAC.pipeline.cpac_pipeline.run(\"run_config.yml\" , \"CPAC_subject_list.yml\", \"$SGE_TASK_ID\" , \"/home2/data/Projects/CWAS/share/adhd200_rerun/02_preprocess/cluster_temp_files/strategies.obj\", \"/path/to/mask_definitions_file\" , \"/home2/data/Projects/NKI_TRT_paper/NewAnalysisWithCPAC/configs/configs_for_dual_regression_20130325/roiSpecification.txt\", \"/home2/data/Projects/NKI_TRT_paper/NewAnalysisWithCPAC/configs/configs_for_dual_regression_20130325/template_for_DC.txt\") " 
